name = "BottleNeckFlow"
uuid = "b5943f10-eebc-4580-8055-7a9e033eeb3e"
authors = ["tcarion <tristancarion@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"

[compat]
Makie = "0.16"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
